server:
  port: 8086
spring:
  mvc:
    view:
      prefix: /
      suffix: jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.1.205:3306/fdasystem?autoReconnect=true
    username: dev_ess
    password: dev_ess
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  dubbo:
    application:            #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
      name: Provide
    registry:                 #注册中心配置，用于配置连接注册中心相关信息。
      address: zookeeper://127.0.0.1:2181
    protocol:     #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受。
      name: dubbo
      port: 20880
    scan: com.wei.dubbo.provider  #服务暴露与发现消费所在的package
mybatis:
  mapper-locations: classpath:com/wei/dubbo/provider/mapper/*.xml
  type-aliases-package: classpath:com/wei/dubbo/provider/bo

  #log4j打印
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



my:
  name: